# Generated by Django 3.2.10 on 2021-12-08 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_topping'),
    ]

    operations = [
        migrations.AddField(
            model_name='topping',
            name='name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
